//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace urlShortener_eb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class urlshortener_history
    {
        public int Id { get; set; }
        public string shortened_url { get; set; }
        public string previous_url { get; set; }
        public Nullable<int> click_count { get; set; }
        public Nullable<System.DateTime> expiration_time { get; set; }
        public string expirate_time { get; set; }
    }
}
